# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Recep/Desktop/python/pyqt5.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ServoMotorController(object):
    def setupUi(self, ServoMotorController):
        ServoMotorController.setObjectName("ServoMotorController")
        ServoMotorController.setWindowModality(QtCore.Qt.NonModal)
        ServoMotorController.resize(515, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/pp.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ServoMotorController.setWindowIcon(icon)
        ServoMotorController.setStyleSheet("background-image: url(:/newPrefix/pp.jpg);")
        self.centralwidget = QtWidgets.QWidget(ServoMotorController)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.baudrate = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.baudrate.setFont(font)
        self.baudrate.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.baudrate.setObjectName("baudrate")
        self.gridLayout.addWidget(self.baudrate, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setToolTip("")
        self.comboBox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.port = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.port.setFont(font)
        self.port.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.port.setObjectName("port")
        self.gridLayout.addWidget(self.port, 0, 0, 1, 1)
        self.openport = QtWidgets.QPushButton(self.centralwidget)
        self.openport.setStyleSheet("color: rgb(255, 255, 255);")
        self.openport.setObjectName("openport")
        self.gridLayout.addWidget(self.openport, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setEnabled(True)
        self.comboBox_2.setToolTip("")
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setStyleSheet("")
        self.horizontalSlider.setMaximum(180)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.ServoMotorDegree = QtWidgets.QSpinBox(self.centralwidget)
        self.ServoMotorDegree.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ServoMotorDegree.setMaximum(180)
        self.ServoMotorDegree.setObjectName("ServoMotorDegree")
        self.horizontalLayout.addWidget(self.ServoMotorDegree)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setMaximum(180)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_2)
        self.ServoMotorDegree_5 = QtWidgets.QSpinBox(self.centralwidget)
        self.ServoMotorDegree_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ServoMotorDegree_5.setMaximum(180)
        self.ServoMotorDegree_5.setObjectName("ServoMotorDegree_5")
        self.horizontalLayout_2.addWidget(self.ServoMotorDegree_5)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setMaximum(180)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_3)
        self.ServoMotorDegree_6 = QtWidgets.QSpinBox(self.centralwidget)
        self.ServoMotorDegree_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ServoMotorDegree_6.setMaximum(180)
        self.ServoMotorDegree_6.setObjectName("ServoMotorDegree_6")
        self.horizontalLayout_3.addWidget(self.ServoMotorDegree_6)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_4.setMaximum(180)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_4)
        self.ServoMotorDegree_7 = QtWidgets.QSpinBox(self.centralwidget)
        self.ServoMotorDegree_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ServoMotorDegree_7.setMaximum(180)
        self.ServoMotorDegree_7.setObjectName("ServoMotorDegree_7")
        self.horizontalLayout_4.addWidget(self.ServoMotorDegree_7)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.horizontalLayout_5.addLayout(self.formLayout)
        ServoMotorController.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ServoMotorController)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 26))
        self.menubar.setObjectName("menubar")
        ServoMotorController.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ServoMotorController)
        self.statusbar.setObjectName("statusbar")
        ServoMotorController.setStatusBar(self.statusbar)

        self.retranslateUi(ServoMotorController)
        self.comboBox.setCurrentIndex(4)
        self.comboBox_2.setCurrentIndex(5)
        self.horizontalSlider.valueChanged['int'].connect(self.ServoMotorDegree.setValue)
        self.horizontalSlider_2.valueChanged['int'].connect(self.ServoMotorDegree_5.setValue)
        self.horizontalSlider_3.valueChanged['int'].connect(self.ServoMotorDegree_6.setValue)
        self.horizontalSlider_4.valueChanged['int'].connect(self.ServoMotorDegree_7.setValue)
        QtCore.QMetaObject.connectSlotsByName(ServoMotorController)

    def retranslateUi(self, ServoMotorController):
        _translate = QtCore.QCoreApplication.translate
        ServoMotorController.setWindowTitle(_translate("ServoMotorController", "Servo Motor Controller"))
        self.baudrate.setText(_translate("ServoMotorController", "BAUD RATE"))
        self.comboBox.setCurrentText(_translate("ServoMotorController", "COM5"))
        self.comboBox.setItemText(0, _translate("ServoMotorController", "COM1"))
        self.comboBox.setItemText(1, _translate("ServoMotorController", "COM2"))
        self.comboBox.setItemText(2, _translate("ServoMotorController", "COM3"))
        self.comboBox.setItemText(3, _translate("ServoMotorController", "COM4"))
        self.comboBox.setItemText(4, _translate("ServoMotorController", "COM5"))
        self.comboBox.setItemText(5, _translate("ServoMotorController", "COM6"))
        self.comboBox.setItemText(6, _translate("ServoMotorController", "COM7"))
        self.comboBox.setItemText(7, _translate("ServoMotorController", "COM8"))
        self.comboBox.setItemText(8, _translate("ServoMotorController", "COM9"))
        self.port.setText(_translate("ServoMotorController", "PORT"))
        self.openport.setText(_translate("ServoMotorController", "OPEN PORT"))
        self.pushButton_2.setText(_translate("ServoMotorController", "CLOSE PORT"))
        self.comboBox_2.setCurrentText(_translate("ServoMotorController", "9600"))
        self.comboBox_2.setItemText(0, _translate("ServoMotorController", "300"))
        self.comboBox_2.setItemText(1, _translate("ServoMotorController", "600"))
        self.comboBox_2.setItemText(2, _translate("ServoMotorController", "1200"))
        self.comboBox_2.setItemText(3, _translate("ServoMotorController", "2400"))
        self.comboBox_2.setItemText(4, _translate("ServoMotorController", "4800"))
        self.comboBox_2.setItemText(5, _translate("ServoMotorController", "9600"))
        self.comboBox_2.setItemText(6, _translate("ServoMotorController", "14400"))
        self.comboBox_2.setItemText(7, _translate("ServoMotorController", "19200"))
        self.comboBox_2.setItemText(8, _translate("ServoMotorController", "28800"))
        self.comboBox_2.setItemText(9, _translate("ServoMotorController", "38400"))
        self.comboBox_2.setItemText(10, _translate("ServoMotorController", "57600"))
        self.comboBox_2.setItemText(11, _translate("ServoMotorController", "115200"))
        self.label_2.setText(_translate("ServoMotorController", "SERVO 1"))
        self.label_3.setText(_translate("ServoMotorController", "SERVO 2"))
        self.label_5.setText(_translate("ServoMotorController", "SERVO 3"))
        self.label_4.setText(_translate("ServoMotorController", "SERVO 4"))
        self.label.setText(_translate("ServoMotorController", "      SERVO MOTOR DEGREES"))

import icons_rc
